spring:
  application:
    name: yuan-ai-code-mother-backend
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan:
        - com.yuanc.yuanaicodemother.controller
knife4j:
  enable: true
  setting:
    language: zh_cn